import { PlaceCategory } from '../types/map-types';

export const CATEGORIES: PlaceCategory[] = [
  {
    id: 'restaurants',
    label: 'Restaurants',
    query: 'restaurant',
    emoji: '🍽️',
    color: '#ea4335',
    overpass: ['amenity=restaurant', 'amenity=fast_food', 'amenity=food_court'],
  },
  {
    id: 'coffee',
    label: 'Coffee',
    query: 'cafe',
    emoji: '☕',
    color: '#8d6e63',
    overpass: ['amenity=cafe'],
  },
  {
    id: 'gas',
    label: 'Gas',
    query: 'gas station',
    emoji: '⛽',
    color: '#1a73e8',
    overpass: ['amenity=fuel'],
  },
  {
    id: 'hotels',
    label: 'Hotels',
    query: 'hotel',
    emoji: '🏨',
    color: '#9c27b0',
    overpass: ['tourism=hotel', 'tourism=motel', 'tourism=hostel', 'tourism=guest_house'],
  },
  {
    id: 'groceries',
    label: 'Groceries',
    query: 'supermarket',
    emoji: '🛒',
    color: '#34a853',
    overpass: ['shop=supermarket', 'shop=convenience', 'shop=greengrocer'],
  },
  {
    id: 'pharmacy',
    label: 'Pharmacy',
    query: 'pharmacy',
    emoji: '💊',
    color: '#00acc1',
    overpass: ['amenity=pharmacy'],
  },
  {
    id: 'atms',
    label: 'ATMs',
    query: 'atm',
    emoji: '🏧',
    color: '#00897b',
    overpass: ['amenity=atm', 'amenity=bank'],
  },
  {
    id: 'parks',
    label: 'Parks',
    query: 'park',
    emoji: '🌳',
    color: '#43a047',
    overpass: ['leisure=park', 'leisure=garden', 'leisure=nature_reserve'],
  },
  {
    id: 'shopping',
    label: 'Shopping',
    query: 'mall',
    emoji: '🛍️',
    color: '#e91e63',
    overpass: ['shop=mall', 'shop=department_store', 'shop=clothes'],
  },
  {
    id: 'hospitals',
    label: 'Hospitals',
    query: 'hospital',
    emoji: '🏥',
    color: '#d32f2f',
    overpass: ['amenity=hospital', 'amenity=clinic'],
  },
  {
    id: 'transit',
    label: 'Transit',
    query: 'subway station',
    emoji: '🚇',
    color: '#f57c00',
    overpass: [
      'railway=station',
      'railway=subway_entrance',
      'amenity=bus_station',
      'highway=bus_stop',
    ],
  },
  {
    id: 'gyms',
    label: 'Gyms',
    query: 'gym',
    emoji: '💪',
    color: '#5e35b1',
    overpass: ['leisure=fitness_centre', 'leisure=sports_centre'],
  },
];
